### ISSUE TITLE
(00.148418) Error (criu/page-xfer.c:246): Hole 0x3ff000/4096 not found in parent

### ISSUE THREAD

**Issue by avagin** [xemul/criu#216]
https://ci.openvz.org/job/CRIU/job/CRIU-x86_64-pre-dump/branch/criu-dev/947/
```
======================= Run zdtm/transition/maps008 in h =======================
Start test
Test is SUID
./maps008 --pidfile=maps008.pid --outfile=maps008.out
Run criu pre-dump
Run criu pre-dump
Run criu pre-dump
Run criu dump
=[log]=> dump/zdtm/transition/maps008/24/4/dump.log
------------------------ grep Error ------------------------
(00.148418) Error (criu/page-xfer.c:246): Hole 0x3ff000/4096 not found in parent
(00.181735) Error (criu/cr-dump.c:1674): Dumping FAILED.
------------------------ ERROR OVER ------------------------
################ Test zdtm/transition/maps008 FAIL at CRIU dump ################
Send the 9 signal to  24
Wait for zdtm/transition/maps008(24) to die for 0.100000
```

Cc: @rppt @adrianreber

**Comment by rppt** [comment]
@avagin, logs?

**Comment by avagin** [comment]
Cc: @eabatalov

**Comment by avagin** [comment]
https://www.dropbox.com/s/isijwijxc5qpxlr/criu-pre-dump.sh-6363c55d941d0d50b1ec5fe9097aee2b32866f1b-09130633.tar.gz?dl=0

**Comment by eabatalov** [comment]
I've investigated logs and dumps from dropbox share. This bug takes place because of some race condition. anon shmem dumping code doesn't have few places with possible races. One of them is usage mincore. The page we've lost in parent dump could be swapped out and we won't dump it in this case.
For me it looks like the root cause can't be reconstructed from the data we have.

**Comment by xemul** [comment]
Let's consider this as #218
