### ISSUE TITLE
Error (criu/vdso.c:460): vdso: Compat vDSO helper didn't exit, status: 139

### ISSUE THREAD

**Issue by avagin** [xemul/criu#290]
```
+ ./test/zdtm.py run -t zdtm/static/env00 --rpc
profiling:/home/travis/build/avagin/criu/criu/cr-service.gcda:Merge mismatch for function 15
=== Run 1/1 ================ zdtm/static/env00

========================== Run zdtm/static/env00 in h ==========================
Start test
./env00 --pidfile=env00.pid --outfile=env00.out --envname=ENV_00_TEST
Run criu dump
Fail
=[log]=> dump/zdtm/static/env00/32/1/dump.log
------------------------ grep Error ------------------------
(00.065764) Error (criu/vdso.c:460): vdso: Compat vDSO helper didn't exit, status: 139
(00.065825) Error (criu/vdso.c:485): vdso: Failed to mmap compatible vdso with helper process
(00.065857) Error (criu/vdso.c:522): vdso: Failed to fill compat vdso symtable
(00.065931) Error (criu/cr-dump.c:1685): Dumping FAILED.
------------------------ ERROR OVER ------------------------
################### Test zdtm/static/env00 FAIL at CRIU dump ###################
```

https://api.travis-ci.org/jobs/209874345/log.txt?deansi=true

Cc: @cyrillos @0x7f454c46

**Comment by avagin** [comment]
It is linux-next (4.11.0-rc1-next-20170310)

**Comment by 0x7f454c46** [comment]
Looks like a reproducion for #273, I'll take a look, thanks.

**Comment by 0x7f454c46** [comment]
Ok, so yesterday I've tried to reproduce it on next-20170310 with criu-dev, but no luck.
Fortunately, the log above gives a clue:
> (00.065764) Error (criu/vdso.c:460): vdso: Compat vDSO helper didn't exit, status: 139
status 139,  not exited, looking at macro definitions:
```
/* Nonzero if STATUS indicates termination by a signal.  */
#define __WIFSIGNALED(status) \
  (((signed char) (((status) & 0x7f) + 1) >> 1) > 0)
/* If WIFSIGNALED(STATUS), the terminating signal.  */
#define	__WTERMSIG(status)	((status) & 0x7f)
```
`139 & 0x7f == 11`,  that means that helper for compat vdso was killed with 11 signal (SIGSEGV).

Looking at the code, I do not see anything quite suspicious.
I've two conjectures where it could segfault in the helper:
1. Using `syscall(__NR_<sysname>,...)` from Glibc after unmapping vdso. I was trying to keep it simple as possible, but maybe it's not safe to call `syscall()` and `memcpy()` from Glibc with unmapped vdso/vvar, even for simple syscalls as munmap(), kill(), read(), write(), exit().
2. By some reason memcpy() source is not mapped. That looks impossible as we're reading from vma which addresses we just read from /proc/.../maps, but still, it's a place where something could have gone wrong.

I'll address this conjectures with patches which will: (a) use pie library for raw syscalls in helper instead of Glibc's `syscall()` and `memcpy()`; (b) add log printing for %rip address from u_context on caught SIGSEGV from the helper. This way it'll be easier to find what's wrong.
@avagin, I guess, this is not simply reproducible on your environment, right?
Looking at #273 - it also was caught on env00 test, so I'll leave C/R on the test spinning during a night on this week, let's see if I can reproduce it locally with some effort.
