### ISSUE TITLE
"Error (criu/lsm.c:181): mismatched lsm types and lsm profile specified" after criu upgrade

### ISSUE THREAD

**Issue by tswift242** [xemul/criu#323]
After upgrading from criu 2.12.1 to 3.2, I now get the error "Error (criu/lsm.c:181): mismatched lsm types and lsm profile specified" when trying to restore a docker container running my application. I have attached the dump and restore logs (slightly censored). I'm running docker version 17.03.0-ce.

The only lsm profile I'm running on my docker container is the docker-default AppArmor profile (as you can see from the dump log).

[dump.txt](https://github.com/xemul/criu/files/1092575/dump.txt)
[restore.txt](https://github.com/xemul/criu/files/1092576/restore.txt)

**Comment by xemul** [comment]
Can you downgrade criu back to 2.12 and show dump (and restore) logs? And also show the contents of inventory.img for both cases :)

**Comment by xemul** [comment]
It looks like the host-side LSM profile is not checked due to kerndat cache (it was introduced in 3.1). So let's try the [branch with the fix](https://github.com/xemul/criu/commits/master-lsm-kerndat).

It's not a single patch since the LSM mode in question is 3 variables, so I had to first clean 2 of them :D

**Comment by tswift242** [comment]
@xemul It looks like that fixed it! Thanks!

**Comment by xemul** [comment]
Fixed in 3.2.1
